/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IPublius, IPubliusInterface } from "../../contracts/IPublius";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_section",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_chapterName",
        type: "string",
      },
      {
        internalType: "string",
        name: "_chapterImage",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_chapterId",
        type: "uint256",
      },
      {
        internalType: "string[]",
        name: "_pageNames",
        type: "string[]",
      },
      {
        internalType: "string[]",
        name: "_pageContent",
        type: "string[]",
      },
    ],
    name: "addChapter",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_section",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_chapter",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "_pageName",
        type: "string",
      },
      {
        internalType: "string",
        name: "_pageContent",
        type: "string",
      },
    ],
    name: "addPage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "tokenURI",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPublius__factory {
  static readonly abi = _abi;
  static createInterface(): IPubliusInterface {
    return new utils.Interface(_abi) as IPubliusInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPublius {
    return new Contract(address, _abi, signerOrProvider) as IPublius;
  }
}
