/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iPubliusSol from "./IPublius.sol";
export type { iPubliusSol };
export type { Publius } from "./Publius";
export type { PubliusBeacon } from "./PubliusBeacon";
export type { PubliusFactory } from "./PubliusFactory";
