/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface IPubliusInterface extends utils.Interface {
  functions: {
    "addChapter(uint256,string,string,uint256,string[],string[],string[])": FunctionFragment;
    "addPage(uint256,string,string,string)": FunctionFragment;
    "addSection(bytes,bytes,bytes)": FunctionFragment;
    "getPage(uint256,uint256)": FunctionFragment;
    "initialize(address,string,string)": FunctionFragment;
    "mint(uint256)": FunctionFragment;
    "tokenURI()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addChapter"
      | "addPage"
      | "addSection"
      | "getPage"
      | "initialize"
      | "mint"
      | "tokenURI"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addChapter",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>[],
      PromiseOrValue<string>[],
      PromiseOrValue<string>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addPage",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "addSection",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getPage",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "tokenURI", values?: undefined): string;

  decodeFunctionResult(functionFragment: "addChapter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addPage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addSection", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPage", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenURI", data: BytesLike): Result;

  events: {};
}

export interface IPublius extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPubliusInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addChapter(
      _sectionId: PromiseOrValue<BigNumberish>,
      _chapterName: PromiseOrValue<string>,
      _chapterImage: PromiseOrValue<string>,
      _chapterId: PromiseOrValue<BigNumberish>,
      _pageNames: PromiseOrValue<string>[],
      _pageContent: PromiseOrValue<string>[],
      _pageIds: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addPage(
      _chapter: PromiseOrValue<BigNumberish>,
      _pageName: PromiseOrValue<string>,
      _pageContent: PromiseOrValue<string>,
      _pageId: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addSection(
      _sectionInfo: PromiseOrValue<BytesLike>,
      _chapterInfo: PromiseOrValue<BytesLike>,
      _pageInfo: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getPage(
      _chapter: PromiseOrValue<BigNumberish>,
      _pageId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        pageName: string;
        pageId: string;
        pageContent: string;
      }
    >;

    initialize(
      _publicationAuthor: PromiseOrValue<string>,
      _publicationName: PromiseOrValue<string>,
      _publicationCoverImage: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    mint(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    tokenURI(overrides?: CallOverrides): Promise<[string]>;
  };

  addChapter(
    _sectionId: PromiseOrValue<BigNumberish>,
    _chapterName: PromiseOrValue<string>,
    _chapterImage: PromiseOrValue<string>,
    _chapterId: PromiseOrValue<BigNumberish>,
    _pageNames: PromiseOrValue<string>[],
    _pageContent: PromiseOrValue<string>[],
    _pageIds: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addPage(
    _chapter: PromiseOrValue<BigNumberish>,
    _pageName: PromiseOrValue<string>,
    _pageContent: PromiseOrValue<string>,
    _pageId: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addSection(
    _sectionInfo: PromiseOrValue<BytesLike>,
    _chapterInfo: PromiseOrValue<BytesLike>,
    _pageInfo: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getPage(
    _chapter: PromiseOrValue<BigNumberish>,
    _pageId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string] & {
      pageName: string;
      pageId: string;
      pageContent: string;
    }
  >;

  initialize(
    _publicationAuthor: PromiseOrValue<string>,
    _publicationName: PromiseOrValue<string>,
    _publicationCoverImage: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  mint(
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  tokenURI(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addChapter(
      _sectionId: PromiseOrValue<BigNumberish>,
      _chapterName: PromiseOrValue<string>,
      _chapterImage: PromiseOrValue<string>,
      _chapterId: PromiseOrValue<BigNumberish>,
      _pageNames: PromiseOrValue<string>[],
      _pageContent: PromiseOrValue<string>[],
      _pageIds: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    addPage(
      _chapter: PromiseOrValue<BigNumberish>,
      _pageName: PromiseOrValue<string>,
      _pageContent: PromiseOrValue<string>,
      _pageId: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addSection(
      _sectionInfo: PromiseOrValue<BytesLike>,
      _chapterInfo: PromiseOrValue<BytesLike>,
      _pageInfo: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;

    getPage(
      _chapter: PromiseOrValue<BigNumberish>,
      _pageId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string] & {
        pageName: string;
        pageId: string;
        pageContent: string;
      }
    >;

    initialize(
      _publicationAuthor: PromiseOrValue<string>,
      _publicationName: PromiseOrValue<string>,
      _publicationCoverImage: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    mint(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    tokenURI(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    addChapter(
      _sectionId: PromiseOrValue<BigNumberish>,
      _chapterName: PromiseOrValue<string>,
      _chapterImage: PromiseOrValue<string>,
      _chapterId: PromiseOrValue<BigNumberish>,
      _pageNames: PromiseOrValue<string>[],
      _pageContent: PromiseOrValue<string>[],
      _pageIds: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addPage(
      _chapter: PromiseOrValue<BigNumberish>,
      _pageName: PromiseOrValue<string>,
      _pageContent: PromiseOrValue<string>,
      _pageId: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addSection(
      _sectionInfo: PromiseOrValue<BytesLike>,
      _chapterInfo: PromiseOrValue<BytesLike>,
      _pageInfo: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getPage(
      _chapter: PromiseOrValue<BigNumberish>,
      _pageId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _publicationAuthor: PromiseOrValue<string>,
      _publicationName: PromiseOrValue<string>,
      _publicationCoverImage: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    mint(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    tokenURI(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addChapter(
      _sectionId: PromiseOrValue<BigNumberish>,
      _chapterName: PromiseOrValue<string>,
      _chapterImage: PromiseOrValue<string>,
      _chapterId: PromiseOrValue<BigNumberish>,
      _pageNames: PromiseOrValue<string>[],
      _pageContent: PromiseOrValue<string>[],
      _pageIds: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addPage(
      _chapter: PromiseOrValue<BigNumberish>,
      _pageName: PromiseOrValue<string>,
      _pageContent: PromiseOrValue<string>,
      _pageId: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addSection(
      _sectionInfo: PromiseOrValue<BytesLike>,
      _chapterInfo: PromiseOrValue<BytesLike>,
      _pageInfo: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getPage(
      _chapter: PromiseOrValue<BigNumberish>,
      _pageId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _publicationAuthor: PromiseOrValue<string>,
      _publicationName: PromiseOrValue<string>,
      _publicationCoverImage: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    mint(
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    tokenURI(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
