/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface PubliusFactoryInterface extends utils.Interface {
  functions: {
    "createPublication(uint256,address,string,string,string,uint256)": FunctionFragment;
    "getBeacon()": FunctionFragment;
    "getImplementation()": FunctionFragment;
    "getPublicationAddress(uint256)": FunctionFragment;
    "publicationCount()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "createPublication"
      | "getBeacon"
      | "getImplementation"
      | "getPublicationAddress"
      | "publicationCount"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createPublication",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(functionFragment: "getBeacon", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getImplementation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicationAddress",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "publicationCount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createPublication",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBeacon", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getImplementation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicationAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicationCount",
    data: BytesLike
  ): Result;

  events: {
    "BeaconDeployed(address)": EventFragment;
    "PublicationCreated(uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BeaconDeployed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PublicationCreated"): EventFragment;
}

export interface BeaconDeployedEventObject {
  beaconAddress: string;
}
export type BeaconDeployedEvent = TypedEvent<
  [string],
  BeaconDeployedEventObject
>;

export type BeaconDeployedEventFilter = TypedEventFilter<BeaconDeployedEvent>;

export interface PublicationCreatedEventObject {
  id: BigNumber;
  publicationAddress: string;
}
export type PublicationCreatedEvent = TypedEvent<
  [BigNumber, string],
  PublicationCreatedEventObject
>;

export type PublicationCreatedEventFilter =
  TypedEventFilter<PublicationCreatedEvent>;

export interface PubliusFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PubliusFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createPublication(
      _id: PromiseOrValue<BigNumberish>,
      _publicationAuthorAddress: PromiseOrValue<string>,
      _publicationAuthorName: PromiseOrValue<string>,
      _publicationName: PromiseOrValue<string>,
      _publicationCoverImage: PromiseOrValue<string>,
      _costToMint: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getBeacon(overrides?: CallOverrides): Promise<[string]>;

    getImplementation(overrides?: CallOverrides): Promise<[string]>;

    getPublicationAddress(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    publicationCount(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  createPublication(
    _id: PromiseOrValue<BigNumberish>,
    _publicationAuthorAddress: PromiseOrValue<string>,
    _publicationAuthorName: PromiseOrValue<string>,
    _publicationName: PromiseOrValue<string>,
    _publicationCoverImage: PromiseOrValue<string>,
    _costToMint: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getBeacon(overrides?: CallOverrides): Promise<string>;

  getImplementation(overrides?: CallOverrides): Promise<string>;

  getPublicationAddress(
    _id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  publicationCount(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    createPublication(
      _id: PromiseOrValue<BigNumberish>,
      _publicationAuthorAddress: PromiseOrValue<string>,
      _publicationAuthorName: PromiseOrValue<string>,
      _publicationName: PromiseOrValue<string>,
      _publicationCoverImage: PromiseOrValue<string>,
      _costToMint: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getBeacon(overrides?: CallOverrides): Promise<string>;

    getImplementation(overrides?: CallOverrides): Promise<string>;

    getPublicationAddress(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    publicationCount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "BeaconDeployed(address)"(beaconAddress?: null): BeaconDeployedEventFilter;
    BeaconDeployed(beaconAddress?: null): BeaconDeployedEventFilter;

    "PublicationCreated(uint256,address)"(
      id?: null,
      publicationAddress?: null
    ): PublicationCreatedEventFilter;
    PublicationCreated(
      id?: null,
      publicationAddress?: null
    ): PublicationCreatedEventFilter;
  };

  estimateGas: {
    createPublication(
      _id: PromiseOrValue<BigNumberish>,
      _publicationAuthorAddress: PromiseOrValue<string>,
      _publicationAuthorName: PromiseOrValue<string>,
      _publicationName: PromiseOrValue<string>,
      _publicationCoverImage: PromiseOrValue<string>,
      _costToMint: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getBeacon(overrides?: CallOverrides): Promise<BigNumber>;

    getImplementation(overrides?: CallOverrides): Promise<BigNumber>;

    getPublicationAddress(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    publicationCount(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    createPublication(
      _id: PromiseOrValue<BigNumberish>,
      _publicationAuthorAddress: PromiseOrValue<string>,
      _publicationAuthorName: PromiseOrValue<string>,
      _publicationName: PromiseOrValue<string>,
      _publicationCoverImage: PromiseOrValue<string>,
      _costToMint: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getBeacon(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getImplementation(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPublicationAddress(
      _id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    publicationCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
