/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IPubliusFactoryInterface extends utils.Interface {
  functions: {
    "createPublication(uint256,address,string,string,string,uint256)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "createPublication"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createPublication",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "createPublication",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IPubliusFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPubliusFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    createPublication(
      _id: PromiseOrValue<BigNumberish>,
      _publicationAuthorAddress: PromiseOrValue<string>,
      _publicationAuthorName: PromiseOrValue<string>,
      _publicationName: PromiseOrValue<string>,
      _publicationCoverImage: PromiseOrValue<string>,
      _costToMint: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  createPublication(
    _id: PromiseOrValue<BigNumberish>,
    _publicationAuthorAddress: PromiseOrValue<string>,
    _publicationAuthorName: PromiseOrValue<string>,
    _publicationName: PromiseOrValue<string>,
    _publicationCoverImage: PromiseOrValue<string>,
    _costToMint: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    createPublication(
      _id: PromiseOrValue<BigNumberish>,
      _publicationAuthorAddress: PromiseOrValue<string>,
      _publicationAuthorName: PromiseOrValue<string>,
      _publicationName: PromiseOrValue<string>,
      _publicationCoverImage: PromiseOrValue<string>,
      _costToMint: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    createPublication(
      _id: PromiseOrValue<BigNumberish>,
      _publicationAuthorAddress: PromiseOrValue<string>,
      _publicationAuthorName: PromiseOrValue<string>,
      _publicationName: PromiseOrValue<string>,
      _publicationCoverImage: PromiseOrValue<string>,
      _costToMint: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    createPublication(
      _id: PromiseOrValue<BigNumberish>,
      _publicationAuthorAddress: PromiseOrValue<string>,
      _publicationAuthorName: PromiseOrValue<string>,
      _publicationName: PromiseOrValue<string>,
      _publicationCoverImage: PromiseOrValue<string>,
      _costToMint: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
